# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/keybindings_fps',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/keybindings_fps',
                'lib_path': 'keybindings_fps'},
  'syms': {'keybindings_fps.core': {'keybindings_fps.core.foo': ('core.html#foo', 'keybindings_fps/core.py')}}}
