"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_populate_db_defaults.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/01_populate_db_defaults.ipynb 3
def foo(): pass
