"""This module contains several functions that are used in creating the FastHTML gui that makes the handling of the keybindings database more user friendly."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_gui_helpers.ipynb.

# %% auto 0
__all__ = ['update_binding_order']

# %% ../nbs/03_gui_helpers.ipynb 3
from fasthtml.common import *

# %% ../nbs/03_gui_helpers.ipynb 4
def update_binding_order(db: database,
                         binding_id: int,
                         new_order: int):
    """Update the sort_order of a binding"""
    db.t.bindings.update(dict(id=binding_id, sort_order=new_order))
