"""This module contains several functions that are used in creating the FastHTML gui that makes the handling of the keybindings database more user friendly."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_helpers.ipynb.

# %% auto 0
__all__ = ['get_project_root', 'nav', 'base_layout', 'ex_theme_switcher']

# %% ../nbs/03_helpers.ipynb 3
from fasthtml.common import *
from monsterui.all import *
from fastcore.test import *

# %% ../nbs/03_helpers.ipynb 5
def get_project_root() -> Optional[Path]:
    """Get the project root directory from either notebook or module context"""
    try:
        try:
            get_ipython()
            current = Path.cwd()
        except NameError:
            current = Path(__file__).resolve().parent

        while current != current.parent: # Stop at root directory
            if (current / 'pyproject.toml').exists():
                return current
            current = current.parent
        raise FileNotFoundError("Could not find pyproject.toml in any parent directory")
    except Exception as e:
        print(f"Error finding project root: {str(e)}")
        return None

# %% ../nbs/03_helpers.ipynb 7
def nav():
    """Create a navigation bar"""
    nav = NavBar(
        A("Add Game", href="/add_game"),
        A("Add new action", href="/add_action"),
        A("Edit actions", href="/edit_actions"),
        A("Settings", href="/settings"),
        brand=A("Games", href="/")
        )
    return nav

# %% ../nbs/03_helpers.ipynb 8
def base_layout(content):
    """Base layout with navigation bar"""
    return Container(nav(), Div(content, id="content-area"), id="base-layout")

# %% ../nbs/03_helpers.ipynb 9
def ex_theme_switcher():
    return ThemePicker()
