"""Populate the created database with the default values for 'modifiers', 'actions', 'games', 'game_keys', 'categories' and 'bindings'."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_populate_db_defaults.ipynb.

# %% auto 0
__all__ = ['populate_categories', 'populate_modifiers', 'populate_game_keys', 'setup_fresh_db']

# %% ../nbs/01_populate_db_defaults.ipynb 3
from pathlib import Path
from fasthtml.common import *
from .create_db import *

# %% ../nbs/01_populate_db_defaults.ipynb 4
def populate_categories(db):
    """Populate the categories table with initial data"""
    categories = [
        ('movement', 'Movement related actions'),
        ('combat', 'Combat related actions'),
        ('interaction', 'Manipulate the environment'),
        ('communication', 'Communicate with friends and bots'),
        ('menu', 'Access the menus')
    ]
    
    for name, description in categories:
        db.t.categories.insert(dict(name=name, description=description))


# %% ../nbs/01_populate_db_defaults.ipynb 5
def populate_modifiers(db):
    """Populate the modifiers table with initial data"""
    modifiers = ['tap', 'hold', 'scroll', 'double_tap']
    
    for name in modifiers:
        db.t.modifiers.insert(dict(name=name))

# %% ../nbs/01_populate_db_defaults.ipynb 6
def populate_game_keys(db):
    """Populate the game_keys table with initial data"""
    # Letters
    letters = [chr(i) for i in range(ord('a'), ord('z')+1)]
    
    # Numbers
    numbers = [str(i) for i in range(10)]
    
    # Function keys
    function_keys = [f'f{i}' for i in range(1, 13)]
    
    # Special keys
    special_keys = ['left_alt', 'enter', 'space', 'left_control', 'tab', '.', 
                   'left_shift', 'esc', 'del', ';', '-', '`', '=', "'",
                   'mouse_left', 'mouse_right', 'mouse_side_front', 
                   'mouse_side_back', 'mouse_middle', 'mouse_sniper']
    
    # Add all keys
    for key in letters + numbers + function_keys + special_keys:
        db.t.game_keys.insert(dict(name=key))

# %% ../nbs/01_populate_db_defaults.ipynb 7
def setup_fresh_db():
    """Create a fresh database with all initial data"""
    db = init_db()
    create_tables(db)
    populate_categories(db)
    populate_modifiers(db)
    populate_game_keys(db)
    return db
